const express = require("express");
const app = express();
const bodyParser = require("body-parser");
const nodemailer = require("nodemailer");
const sgTransport = require("nodemailer-sendgrid-transport");
const sendgridTransport = require("nodemailer-sendgrid-transport");
require("dotenv").config();
const PORT = process.env.PORT || 8080;
const cors = require("cors");

app.use(cors());
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));

const transporter = nodemailer.createTransport(
  sendgridTransport({ auth: { api_key: process.env.SENDGRID_API } })
);

app.post("/sendemail", (req, res) => {
  const { name, email, service, message } = req.body;
  console.log(req.body);
  if (!name) {
    return res.status(400).json({ error: "Name not found" });
  }
  if (!email) {
    return res.status(400).json({ error: "email not found" });
  }
  if (!service) {
    return res.status(400).json({ error: "service not found" });
  }
  if (!message) {
    return res.status(400).json({ error: "message not found" });
  }
  transporter.sendMail({
    to: "hendrasyailendra@gmail.com",
    from: "hendrasyailendra@gmail.com",
    subject: "This is autogenerated email",
    html: `<h4>Customer details</h4>
    <ul>
    <li>name : ${name}</li>
    <li>E-mail : ${email}</li>
    <li>Service : ${service}</li>
    <li>Message : ${message}</li>
    </ul>`,
  });

  res.json({ success: "email has been sent" });
});

app.listen(PORT, (req, res) => {
  console.log("connected");
});
